export { default as iconFavorite } from './icons/favorite.png'
export { default as iconMusic } from './icons/music.png'
export { default as iconFind } from './icons/find.png'
export { default as iconAdd } from './icons/add.png'
export { default as iconStar } from './icons/star.png'
export { default as iconClose } from './icons/close.png'
export { default as iconDelete } from './icons/delete.png'
export { default as iconUnFavorite } from './icons/un-favorite.png'
export { default as iconUnAdd} from './icons/un-add.png'